/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import garage.Car;
import garage.Garage;
import garage.GarageException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.actionListeners.AddCarAction;
import view.actionListeners.CancelAction;

/**
 *
 * @author Arakhnor
 */
public class AddCarDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddCarPanel
     */
    private Garage model;
    private CarInformationsPanel infoPanel;
    private JPanel buttonPanel;
    private JButton saveButton;
    private JButton cancelButton;

    public AddCarDialog() {
        initComponents();
    }

    public AddCarDialog(Garage model_, JFrame parent, boolean modal) {

        super(parent, modal);

        this.setLayout(new BorderLayout());
        this.model = model_;

        this.infoPanel = new CarInformationsPanel();
        this.infoPanel.setSize(new Dimension(200, 300));
        saveButton = new JButton("Save");
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    Car car = new Car(infoPanel.getMark(), infoPanel.getModel(), infoPanel.getColor(),
                            infoPanel.getKilometers(), infoPanel.getYear(), infoPanel.getPrice());
                    model.addCar(car);
                    firePropertyChange("CAR_ADDED", null, model);
                    JOptionPane.showMessageDialog(null, "Car Added!");
                    dispose();
                } catch (GarageException ex) {
                    Logger.getLogger(AddCarAction.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(new CancelAction(this));

        buttonPanel = new JPanel();
        buttonPanel.add(saveButton);
        buttonPanel.add(cancelButton);

        this.add(infoPanel, BorderLayout.CENTER);
        this.add(buttonPanel, BorderLayout.SOUTH);

        pack();
    }

    public CarInformationsPanel getInformations() {
        return this.infoPanel;
    }
    
    public void addListener(PropertyChangeListener listener){
        addPropertyChangeListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
